<#
.SYNOPSIS
    Gets available resource types for UTCM
#>
function Get-UTCMResourceTypes {
    [CmdletBinding()]
    param()

    Write-Host "Verified UTCM Resource Types (107 confirmed working):" -ForegroundColor Cyan

    Write-Host "`nEntra ID (13 types):" -ForegroundColor Yellow
    Write-Host "  - microsoft.entra.administrativeunit"
    Write-Host "  - microsoft.entra.application"
    Write-Host "  - microsoft.entra.authorizationpolicy"
    Write-Host "  - microsoft.entra.group"
    Write-Host "  - microsoft.entra.grouplifecyclepolicy"
    Write-Host "  - microsoft.entra.namedlocationpolicy"
    Write-Host "  - microsoft.entra.roledefinition"
    Write-Host "  - microsoft.entra.rolesetting"
    Write-Host "  - microsoft.entra.securitydefaults"
    Write-Host "  - microsoft.entra.serviceprincipal"
    Write-Host "  - microsoft.entra.tenantdetails"
    Write-Host "  - microsoft.entra.tokenlifetimepolicy"
    Write-Host "  - microsoft.entra.user"

    Write-Host "`nExchange Online (47 types):" -ForegroundColor Yellow
    Write-Host "  - microsoft.exchange.accepteddomain"
    Write-Host "  - microsoft.exchange.antiphishpolicy"
    Write-Host "  - microsoft.exchange.antiphishrule"
    Write-Host "  - microsoft.exchange.atppolicyforo365"
    Write-Host "  - microsoft.exchange.authenticationpolicy"
    Write-Host "  - microsoft.exchange.availabilityconfig"
    Write-Host "  - microsoft.exchange.calendarprocessing"
    Write-Host "  - microsoft.exchange.casmailboxplan"
    Write-Host "  - microsoft.exchange.casmailboxsettings"
    Write-Host "  - microsoft.exchange.dataclassification"
    Write-Host "  - microsoft.exchange.dataencryptionpolicy"
    Write-Host "  - microsoft.exchange.distributiongroup"
    Write-Host "  - microsoft.exchange.dkimsigningconfig"
    Write-Host "  - microsoft.exchange.emailaddresspolicy"
    Write-Host "  - microsoft.exchange.groupsettings"
    Write-Host "  - microsoft.exchange.inboundconnector"
    Write-Host "  - microsoft.exchange.irmconfiguration"
    Write-Host "  - microsoft.exchange.journalrule"
    Write-Host "  - microsoft.exchange.mailboxpermission"
    Write-Host "  - microsoft.exchange.mailboxplan"
    Write-Host "  - microsoft.exchange.mailboxsettings"
    Write-Host "  - microsoft.exchange.mailcontact"
    Write-Host "  - microsoft.exchange.mailtips"
    Write-Host "  - microsoft.exchange.malwarefilterpolicy"
    Write-Host "  - microsoft.exchange.malwarefilterrule"
    Write-Host "  - microsoft.exchange.managementrole"
    Write-Host "  - microsoft.exchange.omeconfiguration"
    Write-Host "  - microsoft.exchange.organizationconfig"
    Write-Host "  - microsoft.exchange.outboundconnector"
    Write-Host "  - microsoft.exchange.owamailboxpolicy"
    Write-Host "  - microsoft.exchange.partnerapplication"
    Write-Host "  - microsoft.exchange.place"
    Write-Host "  - microsoft.exchange.policytipconfig"
    Write-Host "  - microsoft.exchange.quarantinepolicy"
    Write-Host "  - microsoft.exchange.recipientpermission"
    Write-Host "  - microsoft.exchange.remotedomain"
    Write-Host "  - microsoft.exchange.reportsubmissionrule"
    Write-Host "  - microsoft.exchange.roleassignmentpolicy"
    Write-Host "  - microsoft.exchange.rolegroup"
    Write-Host "  - microsoft.exchange.safeattachmentpolicy"
    Write-Host "  - microsoft.exchange.safeattachmentrule"
    Write-Host "  - microsoft.exchange.safelinkspolicy"
    Write-Host "  - microsoft.exchange.safelinksrule"
    Write-Host "  - microsoft.exchange.sharedmailbox"
    Write-Host "  - microsoft.exchange.sharingpolicy"
    Write-Host "  - microsoft.exchange.transportconfig"
    Write-Host "  - microsoft.exchange.transportrule"

    Write-Host "`nIntune (4 types):" -ForegroundColor Yellow
    Write-Host "  - microsoft.intune.devicecategory"
    Write-Host "  - microsoft.intune.policysets"
    Write-Host "  - microsoft.intune.roleassignment"
    Write-Host "  - microsoft.intune.roledefinition"

    Write-Host "`nSecurity & Compliance (10 types):" -ForegroundColor Yellow
    Write-Host "  - microsoft.securityandcompliance.caseholdpolicy"
    Write-Host "  - microsoft.securityandcompliance.caseholdrule"
    Write-Host "  - microsoft.securityandcompliance.compliancecase"
    Write-Host "  - microsoft.securityandcompliance.compliancesearch"
    Write-Host "  - microsoft.securityandcompliance.compliancetag"
    Write-Host "  - microsoft.securityandcompliance.dlpcompliancepolicy"
    Write-Host "  - microsoft.securityandcompliance.labelpolicy"
    Write-Host "  - microsoft.securityandcompliance.protectionalert"
    Write-Host "  - microsoft.securityandcompliance.retentioneventtype"
    Write-Host "  - microsoft.securityandcompliance.securityfilter"

    Write-Host "`nTeams (33 types):" -ForegroundColor Yellow
    Write-Host "  - microsoft.teams.appsetuppolicy"
    Write-Host "  - microsoft.teams.callholdpolicy"
    Write-Host "  - microsoft.teams.callingpolicy"
    Write-Host "  - microsoft.teams.callparkpolicy"
    Write-Host "  - microsoft.teams.callqueue"
    Write-Host "  - microsoft.teams.channelspolicy"
    Write-Host "  - microsoft.teams.clientconfiguration"
    Write-Host "  - microsoft.teams.cortanapolicy"
    Write-Host "  - microsoft.teams.eventspolicy"
    Write-Host "  - microsoft.teams.feedbackpolicy"
    Write-Host "  - microsoft.teams.filespolicy"
    Write-Host "  - microsoft.teams.ipphonepolicy"
    Write-Host "  - microsoft.teams.meetingconfiguration"
    Write-Host "  - microsoft.teams.meetingpolicy"
    Write-Host "  - microsoft.teams.messagingpolicy"
    Write-Host "  - microsoft.teams.mobilitypolicy"
    Write-Host "  - microsoft.teams.networkroamingpolicy"
    Write-Host "  - microsoft.teams.onlinevoiceuser"
    Write-Host "  - microsoft.teams.pstnusage"
    Write-Host "  - microsoft.teams.shiftspolicy"
    Write-Host "  - microsoft.teams.templatespolicy"
    Write-Host "  - microsoft.teams.tenantdialplan"
    Write-Host "  - microsoft.teams.tenantnetworkregion"
    Write-Host "  - microsoft.teams.tenantnetworksite"
    Write-Host "  - microsoft.teams.tenantnetworksubnet"
    Write-Host "  - microsoft.teams.translationrule"
    Write-Host "  - microsoft.teams.upgradeconfiguration"
    Write-Host "  - microsoft.teams.upgradepolicy"
    Write-Host "  - microsoft.teams.user"
    Write-Host "  - microsoft.teams.vdipolicy"
    Write-Host "  - microsoft.teams.voiceroute"
    Write-Host "  - microsoft.teams.voiceroutingpolicy"
    Write-Host "  - microsoft.teams.workloadpolicy"

    Write-Host "`nFull schema (270+ types): https://www.schemastore.org/utcm-monitor.json" -ForegroundColor Gray
    Write-Host "107 of 270 types confirmed working. See README for full test results." -ForegroundColor Gray
}
